### ISSUE TITLE
Difference between '/dji_sdk/attitude' and '/dji_sdk/imu (orientation)'

### ISSUE THREAD

**Issue by jungwonkang** [dji-sdk/Onboard-SDK-ROS#175]
Hi, I found that both topics '/dji_sdk/attitude' and '/dji_sdk/imu (orientation)' include quaternion.
What is the exact difference between them? Thanks.

**Comment by libo456** [comment]
Hi there,
You can have a look at /dji_sdk/src/modules/dji_sdk_node_publisher.cpp
There you will see that if you are using a Matrice 100 (hence, function DJISDKNode::dataBroadcastCallback() is used), there is no difference between attitude and IMU, as the latter is just a copy from the first one. However, if you have a N3 autopilot (Matrice 200 or 600), there is a difference, which I guess is caused because of the difference in the hardware.
