### ISSUE TITLE
Entering Joystick mode while mission

### ISSUE THREAD

**Issue by hyonlim** [dji-sdk/Onboard-SDK-ROS#275]
We are trying to implement simple obstacle avoidance logic using DJI OSDK on Matrice 210 RTK such as pause mission and avoid obstacle then resume mission.
 

We are testing basic functionality of DJI OSDK with simulation, executing mission (F-WP mode) with planned route using DJI Pilot app.
 
The problem is when we ask to pause mission and SDK control authority during mission, OSDK reports it is able to pause and take over control authority but vehicle ignores given position command.
Only when stopping mission & P mode enables the same code to work as expected.
 

Only SDK control authority works when vehicle changes to joystick mode?
It seems some mode like F-WP, goHome, ... ignores SDK control authority takeover.
We need to know is there any workaround or something.
 
And also stop or changing mode during the mission removes all the waypoints uploaded, even DJI Pilot knows where it is stopped, requires re-uploading waypoint to resume mission.
Is there any workaround here too?

**Comment by dji-dev** [comment]
Public comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/26764'>Zendesk ticket #26764</a>:<br><br>Dear Customer,

Thank you for contacting DJI.

Does your M210 RTK RC have F mode?
DJI OSDK can only work in P or F mode, which can be referred to https://developer.dji.com/onboard-sdk/documentation/guides/component-guide-control-authority.html
In addition, it is recommended that you use the mission function of DJI OSDK to create and generate waypoints instead of using the DJI Pilot APP, so that you can resume normally after pause.

Thank you for your understanding and support, hope you a delighted life.

Best Regards,
DJI SDK Support Team
