### ISSUE TITLE
cannot success finish catkin_make

### ISSUE THREAD

**Issue by MarkinYuriy** [dji-sdk/Onboard-SDK-ROS#279]
hi, cannot finish catkin_make

image
image

Ubuntu 16.04.2 LTS \n \l
ros kinetic
gcc (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
on raspberry 3b+

![image](https://user-images.githubusercontent.com/10794189/62741099-64027000-ba42-11e9-856d-2a6d983e93b6.png)
![image](https://user-images.githubusercontent.com/10794189/62741108-6e246e80-ba42-11e9-9ae9-ee2c49f30f0f.png)

**Comment by dji-dev** [comment]
Public comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/26903'>Zendesk ticket #26903</a>:<br><br>Dear Customer,

Thank you for contacting DJI.

The error prompted is the lack of related dependencies on the environment and advance sensing package. You need to install the related dependencies prompted. Or you can also change the camke file to -DADVANCED_SENSING to OFF.
 ![](https://djisdksupport.zendesk.com/attachments/token/D8ionYyvWGIsa4H5QWipTYv7x/?name=inline1321864295.png)​
Related dependencies tools:
 ![](https://djisdksupport.zendesk.com/attachments/token/BEG7hJDJGmWOzfyFE3AN7fgmS/?name=inline1534986568.png)​

Thank you for your understanding and support, hope you a delighted life.

Best Regards,
DJI SDK Support Team

**Comment by MarkinYuriy** [comment]
changed
until  failed
![image](https://user-images.githubusercontent.com/10794189/62772543-7f07cb00-baa8-11e9-8892-8e8b51a92539.png)

**Comment by MarkinYuriy** [comment]
![image](https://user-images.githubusercontent.com/10794189/62772781-1ec55900-baa9-11e9-8820-7cbd3242937d.png)

**Comment by dji-dev** [comment]
Public comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/26903'>Zendesk ticket #26903</a>:<br><br>Dear Customer,

Thank you for contacting DJI.

It is recommended that you delete all and recompile according to the OSDK development documentation (https://developer.dji.com/onboard-sdk/documentation/development-workflow/sample-setup.html#ros-onboard-computer). (git clone OSDK-ROS set -DADVANCED_SENSING  to OFF)
In addition, if an error occurs again, advised you can provide a complete log document because no specific error content was found in this log, it is not materially helpful for troubleshooting.

Thank you for your understanding and support, hope you a delighted life.

Best Regards,
DJI SDK Support Team
