### ISSUE TITLE
ROS - flight_setpoint_generic_topic - CONTROL FLAG - 0x4B

### ISSUE THREAD

**Issue by chaitanyantr** [dji-sdk/Onboard-SDK-ROS#289]
I want to use following control flag,

0x40 | Command horizontal velocities | Ground/Body | 30 m/s

0x00 | Command the vertical speed | Ground | -5 to 5 m/s

0x08 | Command yaw rate | Ground | 5⁄6π rad/s

0x02 | Horizontal command is body_FLU frame

0x01 | Actively break to hold position after stop sending setpoint

By doing bit OR the value is 0x4b, but the drone is doing the "spherical rounds" ,to reach a Cartesian point (Outer loop with pid controller) in this control flag.

Any input on the control flag...?

**Comment by dji-dev** [comment]
Public comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/27294'>Zendesk ticket #27294</a>:<br><br>Dear Customer,

Thank you for contacting DJI.

Sorry that I don't particularly understand your questions or requirements.
In order to better understand and help you solve the problem, suggest you click the hyperlink on the right to fill in and submit more complete information about the problem.
https://formcrafts.com/a/dji-developer-feedback-en
The problem description column shall be as detailed as possible, including the following contents:
1. Specific problems or needs
2. What functionality do you want to implement?
3. What is the premise or background of the question?

Thank you for your understanding and support, hope you a delighted life.

Best Regards,
DJI SDK Support Team
