### ISSUE TITLE
Matrice 210 RTK - Ros camera feed dies right after take off

### ISSUE THREAD

**Issue by Asylbeck** [dji-sdk/Onboard-SDK-ROS#295]
ubuntu 16.04, OSDK and OSDK-ROS installed, M210 - activation tool is used.  When the camera feed from zenmuse x5s  runs OK on the ground, but as soon as we take off it dies.  I glue gunned the USB cables and made sure I can fly and record a rosbag indoors, but as soon as we go outdoors and try to fly with RTK-GPS and record main camera images topic - it freezes after a few seconds after take off.  There is no error - just says the decoder timed out on the output.

**Comment by dji-dev** [comment]
Public comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/28737'>Zendesk ticket #28737</a>:<br><br>Dear Customer,

Thank you for contacting DJI.

In order to better understand and help you solve the problem, suggest you click the hyperlink on the right to fill in and submit more complete information about the problem.
https://formcrafts.com/a/dji-developer-feedback-en
The problem description column shall be as detailed as possible, including the following contents:
1. Specific model and firmware version of M210
2. The firmware version of x5s
3. OSDK-ROS version
4. Flight record of M210 (exported from DJI Assistan2)
5. The log of program execution
6. Try using the DJI OSDK native sample: demo_camera_gimbal

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
