### ISSUE TITLE
Wrong IMU data in simulation mode

### ISSUE THREAD

**Issue by maxhofidrone** [dji-sdk/Onboard-SDK-ROS#329]
Hi,
I recognized that the IMU topic has some large biases as soon as the simulation mode in DJI Assistant 2 is turned on. Do you know what is happening there? I attached a screenshot of the instant bias as soon as I am entering the simulation mode. I quit this mode after a few seconds and the biases disappear. 
![sim_error_imu](https://user-images.githubusercontent.com/55589716/77674246-89210000-6f8b-11ea-9bfc-57efb845d232.png)

Do you know if this is a constant bias? Can I just divide the simulated IMU values with these biases to get reasonable simulated values? I need the IMU topic for my flight controller and need to test it before in the simulation mode. 
Maybe this issue is related to [Issue 296](https://github.com/dji-sdk/Onboard-SDK-ROS/issues/296).

Thank you very much!

Best regards,

Max

**Comment by dji-dev** [comment]
Agent comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/33116'>Zendesk ticket #33116</a>:<br><br>Dear Customer,

Thank you for contacting DJI.

According to the information you provided, we are unable to determine the cause of the problem. In order to better understand and help you solve the problem, it is recommended that you click the hyperlink on the right to fill in more detailed problem information (Including the necessary product model, system version, SDK version information), https://formcrafts.com/a/dji-developer-feedback-en

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
