### ISSUE TITLE
Why not put on detailed compiling steps to the wiki page?

### ISSUE THREAD

**Issue by zjdavis** [dji-sdk/Onboard-SDK-ROS#36]
Hi, there,

I am quite new to Onboard-sdk and ROS,  I found the steps you described in [Readme] (https://developer.dji.com/onboard-sdk/documentation/github-platform-docs/ROS/README.html) is quite confusing. When talking about how to run the demo, you simply described as:

```
Complete activation:

    Turn on your aircraft and its remote controller (make sure they are paired)
    Download the latest DJI GO application on your mobile device and sign in to your DJI developer account you created earlier
    Run "roslaunch dji_sdk sdk_manifold.launch" to initiate activation command
    Here is how your activation environment will look like: 
```

This would make newbies like me really confusing, you ignored to tell us how to compile it and use it.
I think you should as necessary compiling steps or reference. 

```
make dirs
copy files
catkin_make
```

**Comment by amenon7** [comment]
Hi @zjdavis 

This has been described in the section under Compilation under the same Readme you pointed to: 

"Assuming you have ROS environment installed and configured, cd into your catkin workspace and run catkin_make. Make sure the source code is in the src directory of your catkin workspace. "

Since there are a few steps involved in installing ROS and setting up your ROS environment, we don't get into a lot of detail on our page. We do link you to the [ROS installation and dependency page](http://wiki.ros.org/ROS/Tutorials/InstallingandConfiguringROSEnvironment). 

Thanks.
