### ISSUE TITLE
M100 run sample and get errors

### ISSUE THREAD

**Issue by s40523139** [dji-sdk/Onboard-SDK-ROS#482]
**Hi everyone, I am a novice in using and developing drone.I encounter some error when I try to run the sample.
Here is my hardware setup.**
**I also open DJI Assistant2 while running the sample(as you can see in picture1)**
![1](https://user-images.githubusercontent.com/22387358/139615099-26dc060a-91d2-44f9-b7ba-a3bf48fe9ac7.jpg)                      ![1](https://user-images.githubusercontent.com/22387358/139615283-31d78a32-00ba-402c-bcc4-b4a8b3b1a825.jpg)
![2](https://user-images.githubusercontent.com/22387358/139615304-74093697-0a1d-4cc7-8de0-903dfc90334e.png)

**For the yellow line I have try several SDK version and get same error message (3.1、3.4、3.6、3.8.1)
content of Userconfig.txt  is writing like this
app_id : xxx
app_key : xxx
device :  /dev/ttyUSB0
baudrate : 230400**

![4](https://user-images.githubusercontent.com/22387358/139615539-0002d431-54bd-4ee3-a463-aefc6cb8b04d.png)

**Can anyone give me some advice to solve this?**

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/55494'>Zendesk ticket #55494</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/55494'>Zendesk ticket #55494</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

The error log seems that the version you are using is 4.x, please remove the OSDK first(including the lib), and download again from the following link:
https://github.com/dji-sdk/Onboard-SDK/tree/3.9

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
<br><p><em><small>°°°</small></em></p>

**Comment by s40523139** [comment]
@dji-dev 
Thanks for replying.

But in the terminal I use version 3.8.1 to test the sample.

I have one question, you say remove the OSDK first(including the lib), what is the lib I should remove？Is it mean that I just only remove entire package (ex. OSDK 4.0) I clone from github？　

Thanks for your response!

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/55494'>Zendesk ticket #55494</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

The error from the code:
master branch(OSDK 4.x)：
https://github.com/dji-sdk/Onboard-SDK/blob/d08abe61768f50486ff10bca991c524e6308a011/osdk-core/api/src/dji_vehicle.cpp#L298
 ![](https://djisdksupport.zendesk.com/attachments/token/pDR5QJjLmj0rsuTERsYhltsyH/?name=inline1122769938.png)

If you have install the lib(make install), please remove it from the install path.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team​<br><a href='https://djisdksupport.zendesk.com/attachments/token/pDR5QJjLmj0rsuTERsYhltsyH' target='zd_attach'>inline1122769938.png</a>
<br><p><em><small>°°°</small></em></p>
