### ISSUE TITLE
Does the ROS SDK support the latest DJI Spark?

### ISSUE THREAD

**Issue by chutsu** [dji-sdk/Onboard-SDK-ROS#90]

**Comment by rohitsantdji** [comment]
Hi @chutsu - the ROS SDK will not support the DJI Spark, since it lacks onboard SDK capabilities. You can however use the [iOS](https://github.com/dji-sdk/Mobile-SDK-iOS)/[Android](https://github.com/dji-sdk/Mobile-SDK-Android) SDK to write apps for the Spark.

To help us better understand developer requirements, it would be great to know the use case you were considering for the Spark with ROS!

**Comment by chutsu** [comment]
Thats simple, landing a quadrotor onto a moving platform, similar to the challenge DJI held recently.

**Comment by amenonDJI** [comment]
Closed due to inactivity. Feel free to open another issue if you have any other questions.
